version: "3.5"

services:
  the-scheduler-api:
    image: node:19.5.0
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: postgres13
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_HOST}
    ports:
      - 54340:5432
    volumes:
      - postgres13_scheduler:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres13_scheduler:
